import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Footer from "./_components/footer";

const geistSans = Geist({
  variable: "--font-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex justify-center">
        <main className="w-full max-w-5xl">
          {children}

          <Toaster />
          <Footer />
        </main>
      </body>
    </html>
  );
}
